package qlminimarket;

import Controller.hdbControll;
import Controller.khControll;
import Controller.spController;
import Model.hoadon;
import Model.khachhang;
import Model.sanpham;
import Model.sanphamCT;
import java.awt.print.PrinterException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class HDB extends javax.swing.JFrame {

    String id_HD;
    spController spController = new spController();
    hdbControll controll = new hdbControll();
    khControll controllKH = new khControll();

    private List<hoadon> hoadon;
    private List<sanphamCT> sanphamCT;
    private DefaultTableModel ModelHD;
    private DefaultTableModel ModelspCT;
    int selectedIndex;

    public HDB() {
        initComponents();
        ModelHD = (DefaultTableModel) tbHD.getModel();
        ModelspCT = (DefaultTableModel) tbSPchitiet.getModel();
        showtbHD();
        showtbSPchitiet();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        txtgiaSP = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        txtSLmua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSPchitiet = new javax.swing.JTable();
        txthanhtien1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtSLcon = new javax.swing.JTextField();
        FINDBTN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        btnSAVE = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKhachtra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtTraLai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKH = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtPhaittra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtDiem = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        Menu_Logout = new javax.swing.JMenuItem();
        Menu_Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Thông tin sản phẩm");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Mã sản phẩm");

        txtMaSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaSPMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 218, Short.MAX_VALUE))
                    .addComponent(txtMaSP))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Tên sản phẩm");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtTenSP))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Đơn giá");

        jLabel12.setText("Số lượng mua");

        btnADD.setBackground(new java.awt.Color(255, 153, 51));
        btnADD.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnADD.setForeground(new java.awt.Color(51, 51, 51));
        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Add to basket.png"))); // NOI18N
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        txtSLmua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSLmuaMouseClicked(evt);
            }
        });
        txtSLmua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLmuaActionPerformed(evt);
            }
        });

        jLabel13.setText("Thành tiền");

        tbSPchitiet.setBackground(new java.awt.Color(51, 51, 51));
        tbSPchitiet.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbSPchitiet.setForeground(new java.awt.Color(255, 255, 255));
        tbSPchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Mặt hàng", "SL", "Đơn giá", "Thành tiền"
            }
        ));
        tbSPchitiet.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbSPchitiet.setRowHeight(25);
        tbSPchitiet.setSelectionBackground(new java.awt.Color(255, 153, 51));
        tbSPchitiet.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbSPchitietAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbSPchitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSPchitietMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbSPchitietMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tbSPchitiet);

        txthanhtien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txthanhtien1MouseClicked(evt);
            }
        });
        txthanhtien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthanhtien1ActionPerformed(evt);
            }
        });

        jLabel17.setText("Số lượng hàng còn");

        txtSLcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLconActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgiaSP, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtSLcon)
                    .addComponent(txtSLmua, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txthanhtien1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(btnADD)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtgiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLmua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthanhtien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        FINDBTN.setBackground(new java.awt.Color(255, 153, 51));
        FINDBTN.setFont(new java.awt.Font("Verdana", 1, 8)); // NOI18N
        FINDBTN.setForeground(new java.awt.Color(51, 51, 51));
        FINDBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Search.png"))); // NOI18N
        FINDBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FINDBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FINDBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FINDBTN, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Thông tin hóa đơn BÁN HÀNG");

        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane1.setViewportView(txtBill);

        btnSAVE.setBackground(new java.awt.Color(255, 153, 51));
        btnSAVE.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSAVE.setForeground(new java.awt.Color(51, 51, 51));
        btnSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        btnSAVE.setText("SAVE");
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        btnprint.setBackground(new java.awt.Color(255, 153, 51));
        btnprint.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnprint.setForeground(new java.awt.Color(51, 51, 51));
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print preview.png"))); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(255, 153, 51));
        btnclear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnclear.setForeground(new java.awt.Color(51, 51, 51));
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        tbHD.setBackground(new java.awt.Color(51, 51, 51));
        tbHD.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbHD.setForeground(new java.awt.Color(255, 255, 255));
        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Ngày lập", "Tổng tiền"
            }
        ));
        tbHD.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbHD.setRowHeight(25);
        tbHD.setSelectionBackground(new java.awt.Color(255, 153, 51));
        tbHD.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbHDAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbHDMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tbHD);

        jLabel5.setText("Mã hóa đơn");

        txtMaHD.setText("hdb");

        jLabel8.setText("Tổng tiền ");

        txtTongtien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtTongtienMouseEntered(evt);
            }
        });
        txtTongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongtienActionPerformed(evt);
            }
        });

        jLabel9.setText("Khách trả");

        txtKhachtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachtraActionPerformed(evt);
            }
        });

        jLabel10.setText("Trả lại");

        txtTraLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTraLaiMouseClicked(evt);
            }
        });
        txtTraLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraLaiActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày lập");

        txtDate.setText("mm-dd-yy");
        txtDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDateMouseClicked(evt);
            }
        });

        jLabel7.setText("Khách hàng");

        txtKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtKHMouseEntered(evt);
            }
        });
        txtKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKHActionPerformed(evt);
            }
        });

        jLabel14.setText("Giảm giá");

        txtDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiscountActionPerformed(evt);
            }
        });

        jLabel15.setText("Phải trả");

        txtPhaittra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhaittraActionPerformed(evt);
            }
        });

        jLabel16.setText("Điểm");

        txtDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(txtMaHD)
                    .addComponent(txtKhachtra))
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel10))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTraLai)
                    .addComponent(txtDate, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(txtDiscount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDiem)
                    .addComponent(txtPhaittra)
                    .addComponent(txtKH, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(txtKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPhaittra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel14)
                            .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtKhachtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnclear, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSAVE)
                        .addGap(18, 18, 18)
                        .addComponent(btnclear)))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnprint)))
        );

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home-icon-16.png"))); // NOI18N
        jMenu3.setText("HỆ THỐNG");

        Menu_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-icon-16.png"))); // NOI18N
        Menu_Logout.setText("Đăng xuất");
        Menu_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_LogoutActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Logout);

        Menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Menu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Close-icon-16.png"))); // NOI18N
        Menu_Exit.setText("Thoát");
        Menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ExitActionPerformed(evt);
            }
        });
        jMenu3.add(Menu_Exit);

        jMenuBar1.add(jMenu3);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-view-choose-icon-24.png"))); // NOI18N
        jMenu2.setText("HÓA ĐƠN");
        jMenu2.add(jSeparator1);

        jMenuItem2.setForeground(new java.awt.Color(255, 102, 0));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Price list.png"))); // NOI18N
        jMenuItem2.setText("Hóa đơn bán");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Task list.png"))); // NOI18N
        jMenuItem1.setText("Hóa đơn nhập");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetFrom() {
        txtMaHD.setText("");
        txtTongtien.setText("");
        txtKhachtra.setText("");
        txtTraLai.setText("");
        txtMaSP.setText("");
        txtgiaSP.setText("");
        txtTenSP.setText("");
        txtSLmua.setText("");
        txthanhtien1.setText("");
        txtBill.setText("");
        txtDate.setText("");
        txtKH.setText("");
        txtDiscount.setText("");
        txtPhaittra.setText("");
        txtDiem.setText("");
        txtSLcon.setText("");
    }

    public boolean validateFormHD() {
        if (txtMaHD.getText().isEmpty() || txtDate.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public void setModelsp(sanpham sp) {
        txtTenSP.setText(sp.getTensp());
        txtgiaSP.setText(sp.getGia());
        txtSLcon.setText(String.valueOf(sp.getSoluong()));
    }

    public sanpham getModelSLsp() {
        sanpham sp = new sanpham();
        sp.setMasp(txtMaSP.getText());
        sp.setSoluong(Integer.parseInt(txtSLcon.getText()));
        return sp;
    }

    public hoadon getModel() {
        hoadon hdb = new hoadon();
        hdb.setMaHD(txtMaHD.getText());
        hdb.setDateOrder(txtDate.getText());
        hdb.setTongtien(Integer.parseInt(txtTongtien.getText()));
        return hdb;
    }

    public khachhang getModelDiem() {
        khachhang kh = new khachhang();
        kh.setSdt(txtKH.getText());
        kh.setDiem(Integer.parseInt(txtDiem.getText()));
        return kh;
    }

    public void setModelDiem(khachhang kh) {
        txtDiem.setText(String.valueOf(kh.getDiem()));
    }

    public boolean validateForm() {
        if (txtDiem.getText().isEmpty() || txtKH.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtMaSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaSPMouseClicked

    }//GEN-LAST:event_txtMaSPMouseClicked

    private void FINDBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FINDBTNActionPerformed
        if (txtMaSP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập ID tìm kiếm");
        } else {
            try {
                sanpham sp = spController.findByID(txtMaSP.getText());
                setModelsp(sp);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy");
            }
        }
    }//GEN-LAST:event_FINDBTNActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        sanpham sp1 = getModelSLsp();
        String masp = txtMaSP.getText();
        String tensp = txtTenSP.getText();
        int sl = Integer.parseInt(txtSLmua.getText());
        int gia = Integer.parseInt(txtgiaSP.getText());
        int thanhtien = Integer.parseInt(txthanhtien1.getText());
        try {
            //update SL sp vào db
            if (spController.editSLSP(sp1) > 0) {
                //Thêm sp mua hàng vào bảng
                sanphamCT sp = new sanphamCT(masp, tensp, sl, gia, thanhtien);
                new hdbControll().addsanphamCT(sp);
                JOptionPane.showMessageDialog(this, "Đã update số lượng hàng trong kho");
                showtbSPchitiet();
                txtSLcon.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi:" + e.toString());
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void txtSLmuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSLmuaMouseClicked

    }//GEN-LAST:event_txtSLmuaMouseClicked

    private void txtSLmuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLmuaActionPerformed
        //update tiền cho một sp
        int sl = Integer.parseInt(txtSLmua.getText());
        int gia = Integer.parseInt(txtgiaSP.getText());
        int tt = sl * gia;
        txthanhtien1.setText(String.valueOf(tt));
        //update SL sp
        int con = Integer.parseInt(txtSLcon.getText());
        int mua = Integer.parseInt(txtSLmua.getText());
        int SLmoi = controll.TruSLhang(con, mua);
        txtSLcon.setText(String.valueOf(SLmoi));
    }//GEN-LAST:event_txtSLmuaActionPerformed

    private void tbSPchitietAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbSPchitietAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSPchitietAncestorAdded

    private void tbSPchitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSPchitietMouseClicked
        selectedIndex = tbSPchitiet.getSelectedRow();
        sanphamCT spCT = sanphamCT.get(selectedIndex);
        new hdbControll().delspCT(spCT.getStt());
        showtbSPchitiet();
    }//GEN-LAST:event_tbSPchitietMouseClicked

    private void tbSPchitietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSPchitietMouseEntered

    }//GEN-LAST:event_tbSPchitietMouseEntered

    private void txthanhtien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthanhtien1MouseClicked

    }//GEN-LAST:event_txthanhtien1MouseClicked

    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        if (validateFormHD()) {
            hoadon hd = getModel();
            khachhang kh = getModelDiem();
            try {
                if (controll.addHD(hd) > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    showtbHD();
                    if (controllKH.editDiem(kh) > 0) {
                        JOptionPane.showMessageDialog(this, "Cộng Điểm thành công");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi:" + e.toString());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn hãy nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btnSAVEActionPerformed

    public void bill() {
        int khachtra = Integer.parseInt(txtKhachtra.getText());
        int tralai = Integer.parseInt(txtTraLai.getText());
        int diem = Integer.parseInt(txtDiem.getText());
        int phaitra = Integer.parseInt(txtPhaittra.getText());
        String date = txtDate.getText();
        String sohd = txtMaHD.getText();
        String tennv = txtKH.getText();
        DefaultTableModel model = (DefaultTableModel) tbSPchitiet.getModel();

        //hEADING    
        txtBill.setText(txtBill.getText() + "                                GDL MARKET\n");
        txtBill.setText(txtBill.getText() + "                141 Chiến Thắng, Thanh Trì, Hà Nội\n");
        txtBill.setText(txtBill.getText() + "                             SDT: 0999999999\n");
        txtBill.setText(txtBill.getText() + " ------------------------------------------------------------------------------\n");
        txtBill.setText(txtBill.getText() + "                        HÓA ĐƠN THANH TOÁN                      \n");
        txtBill.setText(txtBill.getText() + "\t      Số hóa đơn: " + sohd + "\n");
        txtBill.setText(txtBill.getText() + " Ngày lập:\t" + date + "\n");
        txtBill.setText(txtBill.getText() + " Khách hàng:\t" + tennv + "\n");
        txtBill.setText(txtBill.getText() + " ------------------------------------------------------------------------------\n");
        txtBill.setText((txtBill.getText() + " Sản phẩm" + "\t" + "Số lượng" + "\t" + "Đơn giá" + "\t" + "Thành tiền" + "\n"));
        txtBill.setText(txtBill.getText() + " ------------------------------------------------------------------------------\n");

        for (int i = 0; i < model.getRowCount(); i++) {
            String tensp = (String) model.getValueAt(i, 2);
            int sl = (int) model.getValueAt(i, 3);
            int gia = (int) model.getValueAt(i, 4);
            int thanhtien = (int) model.getValueAt(i, 5);
            txtBill.setText((txtBill.getText() + " " + tensp + "\t" + sl + "\t" + gia + "\t" + thanhtien + "\n"));
        }
        txtBill.setText(txtBill.getText() + "\n\n");
        txtBill.setText(txtBill.getText() + " ------------------------------------------------------------------------------\n");
        txtBill.setText(txtBill.getText() + "\t\t" + "    Tổng tiền: " + phaitra + "\n");
        txtBill.setText(txtBill.getText() + "\t\t" + "    Khách trả: " + khachtra + "\n");
        txtBill.setText(txtBill.getText() + "\t\t" + "    Tiền thừa: " + tralai + "\n");
        txtBill.setText(txtBill.getText() + "\t\t" + "    Điểm tích: " + diem + "\n\n");
        txtBill.setText(txtBill.getText() + "\t     Xin cảm ơn quý khách\n");
        txtBill.setText(txtBill.getText() + "\t              hẹn gặp lại\n");

    }

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        if (txtMaHD.getText().isEmpty() || txtKhachtra.getText().isEmpty() || txtTraLai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Thông tin còn thiếu");
        } else {
            try {
                bill();
                txtBill.print();
            } catch (PrinterException ex) {
                Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btnprintActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        resetFrom();
    }//GEN-LAST:event_btnclearActionPerformed

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        //
    }//GEN-LAST:event_jMenuItem1MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        HoaDonNhap hdn = new HoaDonNhap();
        hdn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tbHDAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbHDAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHDAncestorAdded

    private void tbHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHDMouseClicked

    private void tbHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHDMouseEntered

    private void txtTongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongtienActionPerformed

    private void txtKhachtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachtraActionPerformed
        int tong = Integer.parseInt(txtPhaittra.getText());
        int Khachtra = Integer.parseInt(txtKhachtra.getText());
        int tl = Khachtra - tong;
        txtTraLai.setText(String.valueOf(tl));
    }//GEN-LAST:event_txtKhachtraActionPerformed

    private void txtTraLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTraLaiMouseClicked

    }//GEN-LAST:event_txtTraLaiMouseClicked

    private void txtTraLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraLaiActionPerformed

    private void txtKHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKHMouseEntered

    }//GEN-LAST:event_txtKHMouseEntered

    private void txtTongtienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTongtienMouseEntered

    }//GEN-LAST:event_txtTongtienMouseEntered

    private void txtPhaittraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhaittraActionPerformed

    }//GEN-LAST:event_txtPhaittraActionPerformed

    private void txtDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemActionPerformed

    }//GEN-LAST:event_txtDiemActionPerformed

    private void txtKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKHActionPerformed
        if (txtKH.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập SĐT tìm kiếm");
        } else {
            try {
                khachhang sdt = controllKH.findBySdt(txtKH.getText());
                setModelDiem(sdt);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy. Thêm khách hàng?");
                KhachHang kh = new KhachHang();
                kh.setVisible(true);
            }
        }
    }//GEN-LAST:event_txtKHActionPerformed

    private void txtDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiscountActionPerformed
        int tong = Integer.parseInt(txtTongtien.getText());
        int giam = Integer.parseInt(txtDiscount.getText());
        int diem = Integer.parseInt(txtDiem.getText());
        //tính số tiền phải trả
        int phaitra = controll.PhaiTra(giam, tong);
        txtPhaittra.setText(String.valueOf(phaitra));
        //update điểm tích lũy
        int t = Integer.parseInt(txtPhaittra.getText());
        int diemmoi = controll.Diemtichluy(t, diem, giam);
        txtDiem.setText(String.valueOf(diemmoi));

        txtKhachtra.setText(String.valueOf(phaitra));
    }//GEN-LAST:event_txtDiscountActionPerformed

    private void Menu_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_LogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_LogoutActionPerformed

    private void Menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ExitActionPerformed
        new Trangchu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_ExitActionPerformed

    private void txtDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDateMouseClicked
        txtDate.setText("");    }//GEN-LAST:event_txtDateMouseClicked

    private void txthanhtien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthanhtien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthanhtien1ActionPerformed

    private void txtSLconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLconActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton FINDBTN;
    private javax.swing.JMenuItem Menu_Exit;
    private javax.swing.JMenuItem Menu_Logout;
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable tbHD;
    private javax.swing.JTable tbSPchitiet;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtKH;
    private javax.swing.JTextField txtKhachtra;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtPhaittra;
    private javax.swing.JTextField txtSLcon;
    private javax.swing.JTextField txtSLmua;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTongtien;
    private javax.swing.JTextField txtTraLai;
    private javax.swing.JTextField txtgiaSP;
    private javax.swing.JTextField txthanhtien1;
    // End of variables declaration//GEN-END:variables

    private void showtbHD() {
        hoadon = new hdbControll().getListHD();
        ModelHD.setRowCount(0);
        for (hoadon hd : hoadon) {
            ModelHD.addRow(new Object[]{
                hd.getMaHD(), hd.getDateOrder(), hd.getTongtien()
            });
        }
    }

    private void showtbSPchitiet() {
        sanphamCT = new hdbControll().getAllsp();
        ModelspCT.setRowCount(0);
        for (sanphamCT sp : sanphamCT) {
            ModelspCT.addRow(new Object[]{
                tbSPchitiet.getRowCount() + 1, sp.getMasp(), sp.getTensp(), sp.getSoluong(), sp.getGia(), sp.getThanhtien()
            });
        }
        int sum = 0;
        for (int i = 0; i < tbSPchitiet.getRowCount(); i++) {
            sum = sum + Integer.parseInt(tbSPchitiet.getValueAt(i, 5).toString());
        }
        txtTongtien.setText(Integer.toString(sum));
        txtMaSP.setText("");
        txtgiaSP.setText("");
        txtTenSP.setText("");
        txtSLmua.setText("");
        txthanhtien1.setText("");
        txtMaSP.requestFocus();
    }

}
