package qlminimarket;

import Controller.hoadonnhapControll;
import Controller.nccControll;
import Controller.spController;
import DB.ConnectDB;
import Model.hoadonnhap;
import Model.hoadonnhap_sp;
import Model.nhacungcap;
import Model.sanpham;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class HoaDonNhap extends javax.swing.JFrame {

    String id_HD;
    hoadonnhapControll controll = new hoadonnhapControll();
    spController spController = new spController();
    nccControll nccControll = new nccControll();

    private List<hoadonnhap> hoadon;
    private List<hoadonnhap_sp> sanphamCT;
    private List<sanpham> sanphamtonkho;
    private DefaultTableModel ModelHD;
    private DefaultTableModel ModelspCT;
    private DefaultTableModel ModelspTonKho;

    int selectedIndex;

    public HoaDonNhap() {
        initComponents();
        ModelHD = (DefaultTableModel) tbHD.getModel();
        ModelspCT = (DefaultTableModel) tbSPchitiet.getModel();
        ModelspTonKho = (DefaultTableModel) tbSPTrongKho.getModel();
        showtbHD();
        showtbSPchitiet();
        showDataCombobox();
        showtbSPtonkho();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtLoai = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        btnADD = new javax.swing.JButton();
        txtSLnhap = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbSPchitiet = new javax.swing.JTable();
        txthanhtien1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        txtSLcon = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbSPTrongKho = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        txtgiaSP = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNCC = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNV = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtKhachtra = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtTraLai = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBill = new javax.swing.JTextArea();
        btnSAVE = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbHD = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu9 = new javax.swing.JMenu();
        Menu_Logout = new javax.swing.JMenuItem();
        Menu_Exit = new javax.swing.JMenuItem();
        BtnHoaDon = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        btnHoaDonNhap = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar3.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Thông tin sản phẩm");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("Mã sản phẩm");

        txtMaSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMaSPMouseClicked(evt);
            }
        });
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên sản phẩm");

        jLabel8.setText("Loại");

        txtLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtLoaiMouseEntered(evt);
            }
        });
        txtLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 51, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Số lượng nhập");

        btnADD.setBackground(new java.awt.Color(255, 153, 51));
        btnADD.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnADD.setForeground(new java.awt.Color(51, 51, 51));
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        txtSLnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSLnhapMouseClicked(evt);
            }
        });
        txtSLnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLnhapActionPerformed(evt);
            }
        });

        jLabel13.setText("Thành tiền");

        tbSPchitiet.setBackground(new java.awt.Color(51, 51, 51));
        tbSPchitiet.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbSPchitiet.setForeground(new java.awt.Color(255, 255, 255));
        tbSPchitiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã SP", "Mặt hàng", "SL", "Đơn giá", "Thành tiền"
            }
        ));
        tbSPchitiet.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbSPchitiet.setRowHeight(25);
        tbSPchitiet.setSelectionBackground(new java.awt.Color(255, 153, 51));
        tbSPchitiet.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbSPchitietAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbSPchitiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSPchitietMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbSPchitietMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(tbSPchitiet);

        txthanhtien1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txthanhtien1MouseClicked(evt);
            }
        });

        jLabel17.setText("Các sản phẩm mua");

        j.setText("Số lượng còn trong kho");

        jLabel19.setText("Các sản phẩm còn trong kho");

        tbSPTrongKho.setBackground(new java.awt.Color(51, 51, 51));
        tbSPTrongKho.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbSPTrongKho.setForeground(new java.awt.Color(255, 255, 255));
        tbSPTrongKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên", "Loại", "SL", "Đơn giá"
            }
        ));
        tbSPTrongKho.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbSPTrongKho.setRowHeight(25);
        tbSPTrongKho.setSelectionBackground(new java.awt.Color(255, 153, 51));
        tbSPTrongKho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbSPTrongKhoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbSPTrongKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSPTrongKhoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbSPTrongKhoMouseEntered(evt);
            }
        });
        jScrollPane5.setViewportView(tbSPTrongKho);

        jLabel11.setText("Đơn giá");

        txtgiaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtgiaSPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txthanhtien1)
                    .addComponent(txtSLnhap, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(txtSLcon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtgiaSP, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(btnADD))
                            .addComponent(j, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 152, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtgiaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(j)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSLnhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthanhtien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnADD)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(377, 377, 377))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Thông tin hóa đơn NHẬP HÀNG");

        jLabel5.setText("Mã hóa đơn");

        jLabel9.setText("Nhà cung cấp");

        txtNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNCCMouseClicked(evt);
            }
        });
        txtNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNCCActionPerformed(evt);
            }
        });

        jLabel10.setText("SĐT");

        txtSDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSDTMouseClicked(evt);
            }
        });
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        jLabel6.setText("Ngày lập");

        jLabel7.setText("ID");

        jLabel14.setText("Tổng tiền ");

        txtTongtien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTongtienActionPerformed(evt);
            }
        });

        jLabel15.setText("Trả");

        txtKhachtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKhachtraActionPerformed(evt);
            }
        });

        jLabel16.setText("Trả lại");

        txtTraLai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTraLaiMouseClicked(evt);
            }
        });
        txtTraLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtKhachtra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTraLai)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtKhachtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(txtTraLai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTongtien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtBill.setColumns(20);
        txtBill.setRows(5);
        jScrollPane1.setViewportView(txtBill);

        btnSAVE.setBackground(new java.awt.Color(255, 153, 51));
        btnSAVE.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnSAVE.setForeground(new java.awt.Color(51, 51, 51));
        btnSAVE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Save.png"))); // NOI18N
        btnSAVE.setText("SAVE");
        btnSAVE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSAVEActionPerformed(evt);
            }
        });

        btnprint.setBackground(new java.awt.Color(255, 153, 51));
        btnprint.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnprint.setForeground(new java.awt.Color(51, 51, 51));
        btnprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Print preview.png"))); // NOI18N
        btnprint.setText("PRINT");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        btnclear.setBackground(new java.awt.Color(255, 153, 51));
        btnclear.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btnclear.setForeground(new java.awt.Color(51, 51, 51));
        btnclear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Refresh.png"))); // NOI18N
        btnclear.setText("CLEAR");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });

        tbHD.setBackground(new java.awt.Color(51, 51, 51));
        tbHD.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        tbHD.setForeground(new java.awt.Color(255, 255, 255));
        tbHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã hóa đơn nhập", "Ngày lập", "Tổng tiền"
            }
        ));
        tbHD.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbHD.setRowHeight(25);
        tbHD.setSelectionBackground(new java.awt.Color(255, 153, 51));
        tbHD.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbHDAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHDMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbHDMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tbHD);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnprint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSAVE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnclear, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSAVE)
                        .addGap(18, 18, 18)
                        .addComponent(btnclear))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnprint)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jMenu9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Home-icon-16.png"))); // NOI18N
        jMenu9.setText("HỆ THỐNG");

        Menu_Logout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        Menu_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout-icon-16.png"))); // NOI18N
        Menu_Logout.setText("Đăng xuất");
        Menu_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_LogoutActionPerformed(evt);
            }
        });
        jMenu9.add(Menu_Logout);

        Menu_Exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_DOWN_MASK));
        Menu_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Close-icon-16.png"))); // NOI18N
        Menu_Exit.setText("Thoát");
        Menu_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_ExitActionPerformed(evt);
            }
        });
        jMenu9.add(Menu_Exit);

        jMenuBar1.add(jMenu9);

        BtnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-view-choose-icon-24.png"))); // NOI18N
        BtnHoaDon.setText("HÓA ĐƠN");

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Price list.png"))); // NOI18N
        jMenu1.setText("Hóa đơn bán");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        BtnHoaDon.add(jMenu1);

        btnHoaDonNhap.setForeground(new java.awt.Color(255, 102, 0));
        btnHoaDonNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Task list.png"))); // NOI18N
        btnHoaDonNhap.setText("Hóa đơn nhập");
        BtnHoaDon.add(btnHoaDonNhap);

        jMenuBar1.add(BtnHoaDon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetFrom() {
        txtMaHD.setText("");
        txtLoai.setSelectedItem(null);
        txtMaSP.setText("");
        txtgiaSP.setText("");
        txtTenSP.setText("");
        txtSLnhap.setText("");
        txthanhtien1.setText("");
        txtBill.setText("");
        txtDate.setText("");
        txtNV.setText("");
        txtTongtien.setText("");
    }

    public boolean validateFormHD() {
        if (txtMaHD.getText().isEmpty() || txtDate.getText().isEmpty()) {
            return false;
        }
        return true;
    }

    public void setModelsp(sanpham sp) {
        txtTenSP.setText(sp.getTensp());
        txtgiaSP.setText(sp.getGia());
        txtSLcon.setText(String.valueOf(sp.getSoluong()));
    }

    public hoadonnhap getModel() {
        hoadonnhap hdb = new hoadonnhap();
        hdb.setMaHD(txtMaHD.getText());
        hdb.setDateOrder(txtDate.getText());
        hdb.setTongtien(Integer.parseInt(txtTongtien.getText()));
        return hdb;
    }

    public sanpham getModelSLsp() {
        sanpham sp = new sanpham();
        sp.setMasp(txtMaSP.getText());
        sp.setSoluong(Integer.parseInt(txtSLcon.getText()));
        return sp;
    }

    public nhacungcap getModelNCC() {
        nhacungcap ncc = new nhacungcap();
        ncc.setSdt(txtSDT.getText());
        ncc.setTonggiaodich(Integer.parseInt(txtTongtien.getText()));
        ncc.setDuno(Integer.parseInt(txtTraLai.getText()));
        return ncc;
    }

    public void setModelNCC(nhacungcap ncc) {
        txtNCC.setText(ncc.getTen());
        txtSDT.setText(ncc.getSdt());
    }

    public void setModelSP(sanpham sp) {
        txtMaSP.setText(sp.getMasp());
        txtTenSP.setText(sp.getTensp());
        txtLoai.setSelectedItem(sp.getLoai());
        txtSLcon.setText(String.valueOf(sp.getSoluong()));
        txtgiaSP.setText(sp.getGia());
    }

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        HDB hdb = new HDB();
        hdb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void txtMaSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMaSPMouseClicked

    }//GEN-LAST:event_txtMaSPMouseClicked

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        String masp = txtMaSP.getText();
        String tensp = txtTenSP.getText();
        int sl = Integer.parseInt(txtSLnhap.getText());
        int gia = Integer.parseInt(txtgiaSP.getText());
        int thanhtien = Integer.parseInt(txthanhtien1.getText());
        sanpham sp1 = getModelSLsp();
        //update SL sp vào db
        if (spController.editSLSP(sp1) > 0) {
            //Thêm sp mua hàng vào bảng
            hoadonnhap_sp sp = new hoadonnhap_sp(masp, tensp, sl, gia, thanhtien);
            new hoadonnhapControll().addsanphamCT(sp);
            showtbSPchitiet();
            showtbSPtonkho();
            JOptionPane.showMessageDialog(this, "Đã update số lượng hàng trong kho");
            txtSLcon.setText("");
        }
    }//GEN-LAST:event_btnADDActionPerformed

    private void txtSLnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSLnhapMouseClicked

    }//GEN-LAST:event_txtSLnhapMouseClicked

    private void txtSLnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLnhapActionPerformed
        int sl = Integer.parseInt(txtSLnhap.getText());
        int gia = Integer.parseInt(txtgiaSP.getText());
        int tt = sl * gia;
        txthanhtien1.setText(String.valueOf(tt));
        //update SL sp
        int con = Integer.parseInt(txtSLcon.getText());
        int nhap = Integer.parseInt(txtSLnhap.getText());
        int SLmoi = controll.CongSLhang(con, nhap);
        txtSLcon.setText(String.valueOf(SLmoi));
    }//GEN-LAST:event_txtSLnhapActionPerformed

    private void tbSPchitietAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbSPchitietAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSPchitietAncestorAdded

    private void tbSPchitietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSPchitietMouseClicked
        selectedIndex = tbSPchitiet.getSelectedRow();
        hoadonnhap_sp spCT = sanphamCT.get(selectedIndex);
        new hoadonnhapControll().delspCT(spCT.getStt());
        showtbSPchitiet();
    }//GEN-LAST:event_tbSPchitietMouseClicked

    private void tbSPchitietMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSPchitietMouseEntered

    }//GEN-LAST:event_tbSPchitietMouseEntered

    private void txthanhtien1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txthanhtien1MouseClicked

    }//GEN-LAST:event_txthanhtien1MouseClicked

    private void txtNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNCCActionPerformed
    }//GEN-LAST:event_txtNCCActionPerformed

    private void txtSDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSDTMouseClicked

    }//GEN-LAST:event_txtSDTMouseClicked

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnSAVEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSAVEActionPerformed
        if (validateFormHD()) {
            hoadonnhap hd = getModel();
            nhacungcap ncc = getModelNCC();
            try {
                if (controll.addHD(hd) > 0) {
                    JOptionPane.showMessageDialog(this, "Thêm thành công");
                    showtbHD();
                    if (nccControll.editNCC(ncc) > 0) {
                        JOptionPane.showMessageDialog(this, "Đã update thông tin nhà cung cấp");
                    }

                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Lỗi:" + e.toString());
                JOptionPane.showMessageDialog(this, "Trùng ID hóa đơn");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Bạn hãy nhập đầy đủ thông tin");
        }
    }//GEN-LAST:event_btnSAVEActionPerformed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        if (txtMaHD.getText().isEmpty() || txtNCC.getText().isEmpty() || txtSDT.getText().isEmpty() || txtNV.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Thông tin còn thiếu");
        } else {
            try {
                bill();
                txtBill.print();
            } catch (PrinterException ex) {
                Logger.getLogger(HoaDon.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnprintActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
        resetFrom();
    }//GEN-LAST:event_btnclearActionPerformed

    private void tbHDAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbHDAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHDAncestorAdded

    private void tbHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHDMouseClicked

    private void tbHDMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHDMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbHDMouseEntered

    private void Menu_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_LogoutActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_LogoutActionPerformed

    private void Menu_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_ExitActionPerformed
        new Trangchu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Menu_ExitActionPerformed

    private void txtTongtienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTongtienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTongtienActionPerformed

    private void txtKhachtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKhachtraActionPerformed
        int tong = Integer.parseInt(txtTongtien.getText());
        int Khachtra = Integer.parseInt(txtKhachtra.getText());
        int tl = Khachtra - tong;
        txtTraLai.setText(String.valueOf(tl));
    }//GEN-LAST:event_txtKhachtraActionPerformed

    private void txtTraLaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTraLaiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraLaiMouseClicked

    private void txtTraLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraLaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraLaiActionPerformed

    private void tbSPTrongKhoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbSPTrongKhoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSPTrongKhoAncestorAdded

    private void tbSPTrongKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSPTrongKhoMouseClicked
        int id = tbSPTrongKho.rowAtPoint(evt.getPoint());
        String id_SP = tbSPTrongKho.getValueAt(id, 0).toString();
        try {
            sanpham sp = spController.findByID(id_SP);
            setModelSP(sp);
            nhacungcap ncc = nccControll.findByNhom((String) txtLoai.getSelectedItem());
            setModelNCC(ncc);
        } catch (Exception ex) {
            Logger.getLogger(SanPham.class.getName()).log(Level.SEVERE, null, ex);
            int result = JOptionPane.showConfirmDialog(this,
                    "Không tìm thấy\nBạn có muốn thêm nhà cung cấp?",
                    "Xác nhận",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                NhaCungCap sp = new NhaCungCap();
                sp.setVisible(true);
            } else if (result == JOptionPane.NO_OPTION) {
            }
        }
    }//GEN-LAST:event_tbSPTrongKhoMouseClicked

    private void tbSPTrongKhoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSPTrongKhoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbSPTrongKhoMouseEntered

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        if (txtMaSP.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nhập ID tìm kiếm");
        } else {
            try {
                sanpham sp = spController.findByID(txtMaSP.getText());
                setModelsp(sp);
            } catch (Exception ex) {
                int result = JOptionPane.showConfirmDialog(this,
                        "Không tìm thấy\nBạn có muốn thêm sản phẩm?",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE);
                if (result == JOptionPane.YES_OPTION) {
                    SanPham sp = new SanPham();
                    sp.setVisible(true);
                } else if (result == JOptionPane.NO_OPTION) {
                }
            }
        }    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoaiActionPerformed
    }//GEN-LAST:event_txtLoaiActionPerformed

    private void txtgiaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtgiaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtgiaSPActionPerformed

    private void txtLoaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLoaiMouseEntered

    }//GEN-LAST:event_txtLoaiMouseEntered

    private void txtNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNCCMouseClicked
    }//GEN-LAST:event_txtNCCMouseClicked

    public void bill() {
        int tongtien = Integer.parseInt(txtTongtien.getText());
        int khachtra = Integer.parseInt(txtKhachtra.getText());
        int tralai = Integer.parseInt(txtTraLai.getText());
        String date = txtDate.getText();
        String sohd = txtMaHD.getText();
        String tennv = txtNV.getText();
        String ncc = txtNCC.getText();
        DefaultTableModel model = (DefaultTableModel) tbSPchitiet.getModel();

        //hEADING    
        txtBill.setText(txtBill.getText() + "                                GDL MARKET\n");
        txtBill.setText(txtBill.getText() + "                141 Chiến Thắng, Thanh Trì, Hà Nội\n");
        txtBill.setText(txtBill.getText() + "                             SDT: 0999999999\n");
        txtBill.setText(txtBill.getText() + " ------------------------------------------------------------------------------\n");
        txtBill.setText(txtBill.getText() + "                        HÓA ĐƠN NHẬP HÀNG                      \n");
        txtBill.setText(txtBill.getText() + "\t      Số hóa đơn: " + sohd + "\n");
        txtBill.setText(txtBill.getText() + " Ngày lập:\t" + date + "\n");
        txtBill.setText(txtBill.getText() + " Thu ngân:\t" + tennv + "\n");
        txtBill.setText(txtBill.getText() + " Nhà cung cấp: " + ncc + "\n");
        txtBill.setText(txtBill.getText() + " ------------------------------------------------------------------------------\n");
        txtBill.setText((txtBill.getText() + " Sản phẩm" + "\t" + "Số lượng" + "\t" + "Đơn giá" + "\t" + "Thành tiền" + "\n"));
        txtBill.setText(txtBill.getText() + " ------------------------------------------------------------------------------\n");

        for (int i = 0; i < model.getRowCount(); i++) {
            String tensp = (String) model.getValueAt(i, 2);
            int sl = (int) model.getValueAt(i, 3);
            int gia = (int) model.getValueAt(i, 4);
            int thanhtien = (int) model.getValueAt(i, 5);
            txtBill.setText((txtBill.getText() + " " + tensp + "\t" + sl + "\t" + gia + "\t" + thanhtien + "\n"));
        }
        txtBill.setText(txtBill.getText() + "\n\n");
        txtBill.setText(txtBill.getText() + "------------------------------------------------------------------------------\n");
        txtBill.setText(txtBill.getText() + "\t\t" + "    Tổng tiền: " + tongtien + "\n");
        txtBill.setText(txtBill.getText() + "\t\t" + "    Trả:           " + khachtra + "\n");
        txtBill.setText(txtBill.getText() + "\t\t" + "    Tiền thừa: " + tralai + "\n\n");
        txtBill.setText(txtBill.getText() + "\t     Xin cảm ơn quý khách\n");
        txtBill.setText(txtBill.getText() + "\t              hẹn gặp lại\n");

    }

    public void setModel(hoadonnhap_sp sp) {
        txtMaSP.setText(sp.getMasp());
        txtTenSP.setText(sp.getTensp());
        txtSLnhap.setText(String.valueOf(sp.getSoluong()));
        txtgiaSP.setText(String.valueOf(sp.getGia()));
        txthanhtien1.setText(String.valueOf(sp.getThanhtien()));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoaDonNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HoaDonNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BtnHoaDon;
    private javax.swing.JMenuItem Menu_Exit;
    private javax.swing.JMenuItem Menu_Logout;
    private javax.swing.JButton btnADD;
    private javax.swing.JMenu btnHoaDonNhap;
    private javax.swing.JButton btnSAVE;
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnprint;
    private javax.swing.JLabel j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tbHD;
    private javax.swing.JTable tbSPTrongKho;
    private javax.swing.JTable tbSPchitiet;
    private javax.swing.JTextArea txtBill;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtKhachtra;
    private javax.swing.JComboBox<String> txtLoai;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNCC;
    private javax.swing.JTextField txtNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSLcon;
    private javax.swing.JTextField txtSLnhap;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTongtien;
    private javax.swing.JTextField txtTraLai;
    private javax.swing.JTextField txtgiaSP;
    private javax.swing.JTextField txthanhtien1;
    // End of variables declaration//GEN-END:variables

    private void showtbHD() {
        hoadon = new hoadonnhapControll().getListHD();
        ModelHD.setRowCount(0);
        for (hoadonnhap hd : hoadon) {
            ModelHD.addRow(new Object[]{
                hd.getMaHD(), hd.getDateOrder(), hd.getTongtien()
            });
        }
    }

    private void showtbSPchitiet() {
        sanphamCT = new hoadonnhapControll().getAllsp();
        ModelspCT.setRowCount(0);
        for (hoadonnhap_sp sp : sanphamCT) {
            ModelspCT.addRow(new Object[]{
                tbSPchitiet.getRowCount() + 1, sp.getMasp(), sp.getTensp(), sp.getSoluong(), sp.getGia(), sp.getThanhtien()
            });
        }
        int sum = 0;
        for (int i = 0; i < tbSPchitiet.getRowCount(); i++) {
            sum = sum + Integer.parseInt(tbSPchitiet.getValueAt(i, 5).toString());
        }
        txtTongtien.setText(Integer.toString(sum));
        txtMaSP.setText("");
        txtgiaSP.setText("");
        txtTenSP.setText("");
        txtSLnhap.setText("");
        txthanhtien1.setText("");
        txtMaSP.requestFocus();
    }

    //đổ dl nhóm ncc vào combobox
    private void showDataCombobox() {
        String sSQL = "SELECT LOAI_SP from CHI_TIET_SAN_PHAM order by LOAI_SP desc";
        try {
            Connection conn = ConnectDB.getDBConnect();
            PreparedStatement sttm = conn.prepareStatement(sSQL);
            ResultSet rs = sttm.executeQuery();
            while (rs.next()) {
                this.txtLoai.addItem(rs.getString("LOAI_SP"));
            }
        } catch (Exception e) {
        }
    }
    // hiển thị sản phẩm trong kho

    private void showtbSPtonkho() {
        sanphamtonkho = new spController().getAllsp();
        ModelspTonKho.setRowCount(0);
        for (sanpham sp : sanphamtonkho) {
            ModelspTonKho.addRow(new Object[]{
                sp.getMasp(), sp.getTensp(), sp.getLoai(), sp.getSoluong(), sp.getGia()
            });
        }
    }
}
